name: Deploy to Aliyun OSS

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: manyuanrong/setup-ossutil@v2.0
      with:
        endpoint: "oss-cn-qingdao.aliyuncs.com"
        access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}
    - run: ossutil -h
    - run: ossutil cp -rf ./ oss://yitaojiang/
